language: elixir

elixir:
  - '1.12.1'

otp_release:
  - '24.0'

env:
  - MIX_ENV=test

addons:
  postgresql: '13.3'

services:
  - 'postgresql'

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

  cache:
  directories:
    - _build
    - deps
